name: deepface-one
services:
- name: api
  source_dir: /
  github:
    repo: saasfactorydev/deepface
    branch: main
  run_command: python main.py
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  envs:
  - key: PORT
    value: "8000"